import type { AnnualLimits, JurisdictionTable } from '../../../../types/tax';
import { FEDERAL_2026, LIMITS_2026 } from './federal-2026';
import { FEDERAL_HISTORY, LIMITS_HISTORY } from './federal-history';
import { flatStateTable } from './states/flat';
import generated from './federal-generated.json';

// Generated by `manage.py sync_tax_tables --frontend-out`; hand-verified years take precedence.
const GENERATED_FEDERAL = normalizeApiTables(
  generated as unknown as Record<number, JurisdictionTable>
);

const BUNDLED_FEDERAL: Record<number, JurisdictionTable> = {
  ...(GENERATED_FEDERAL ?? {}),
  ...FEDERAL_HISTORY,
  2026: FEDERAL_2026,
};
const BUNDLED_LIMITS: Record<number, AnnualLimits> = { ...LIMITS_HISTORY, 2026: LIMITS_2026 };

// API years extend the bundled set; JSON has no Infinity, so an unbounded top bracket is null.
export function normalizeApiTables(
  source: Record<number, JurisdictionTable> | undefined
): Record<number, JurisdictionTable> | undefined {
  if (!source) return undefined;
  const normalized: Record<number, JurisdictionTable> = {};
  for (const [year, table] of Object.entries(source)) {
    const brackets = table.brackets
      ? Object.fromEntries(
          Object.entries(table.brackets).map(([status, rows]) => [
            status,
            rows.map((row) => ({
              rate: row.rate,
              cap: row.cap === null || row.cap === undefined ? Infinity : row.cap,
            })),
          ])
        )
      : undefined;
    normalized[Number(year)] = { ...table, ...(brackets ? { brackets } : {}) } as JurisdictionTable;
  }
  return normalized;
}

export interface TaxTableOverrides {
  federal?: Record<number, JurisdictionTable>;
  limits?: Record<number, AnnualLimits>;
}

const federalFor = (overrides?: TaxTableOverrides) => ({
  ...BUNDLED_FEDERAL,
  ...(overrides?.federal ?? {}),
});

const limitsFor = (overrides?: TaxTableOverrides) => ({
  ...BUNDLED_LIMITS,
  ...(overrides?.limits ?? {}),
});

export const LATEST_TAX_YEAR = Math.max(...Object.keys(BUNDLED_FEDERAL).map(Number));

export const modelledYears = (overrides?: TaxTableOverrides) =>
  Object.keys(federalFor(overrides))
    .map(Number)
    .sort((a, b) => b - a);

export const MODELLED_YEARS = modelledYears();

export const isModelledYear = (year: number, overrides?: TaxTableOverrides) =>
  year in federalFor(overrides);

export type YearResolution =
  | { year: number; kind: 'exact' }
  // Before anything published: the earliest year is the closest defensible stand-in.
  | { year: number; kind: 'earlier'; requested: number }
  // After anything published: next year's figures are not indexed yet.
  | { year: number; kind: 'later'; requested: number };

// Nearest modelled year, not the newest: 2019 models on 2022, not on 2026.
export const resolveTaxYear = (year: number, overrides?: TaxTableOverrides): YearResolution => {
  const years = modelledYears(overrides);
  if (years.includes(year)) return { year, kind: 'exact' };

  const newest = years[0];
  const oldest = years[years.length - 1];
  if (year > newest) return { year: newest, kind: 'later', requested: year };
  if (year < oldest) return { year: oldest, kind: 'earlier', requested: year };

  // A gap inside the range, which should not happen, resolves to the nearest year below.
  const below = years.filter((candidate) => candidate < year);
  return { year: below[0] ?? oldest, kind: 'earlier', requested: year };
};

export const federalTable = (year: number, overrides?: TaxTableOverrides) => {
  const tables = federalFor(overrides);
  return tables[resolveTaxYear(year, overrides).year];
};

// Keyed separately from brackets, so a year with no published limits finds the nearest.
export const annualLimits = (year: number, overrides?: TaxTableOverrides) => {
  const table = limitsFor(overrides);
  const wanted = resolveTaxYear(year, overrides).year;
  if (table[wanted]) return table[wanted];

  const available = Object.keys(table)
    .map(Number)
    .sort((a, b) => Math.abs(a - wanted) - Math.abs(b - wanted));
  return table[available[0]] ?? table[LATEST_TAX_YEAR];
};

// No state is modelled with brackets yet, so every state resolves to its flat rate.
export const stateTable = (
  stateAbbr: string,
  year: number,
  stateTaxRatePercent: Record<string, number>
) => flatStateTable(stateAbbr, stateTaxRatePercent[stateAbbr] ?? 0, year);

export { FEDERAL_2026, LIMITS_2026 };
