import {
  EnvironmentOutlined,
  AimOutlined,
  FileTextOutlined,
  ClockCircleOutlined,
  QuestionCircleOutlined,
  TrophyOutlined,
  BarChartOutlined,
  CalendarOutlined,
  LineChartOutlined,
  ApartmentOutlined,
  BankOutlined,
  ThunderboltOutlined,
} from '@ant-design/icons';
import type { WidgetDefinition } from './types';

export const AVAILABLE_WIDGETS: WidgetDefinition[] = [
  {
    id: 'total',
    name: 'Total Applications',
    description: 'Total number of applications submitted',
    icon: <FileTextOutlined />,
    defaultEnabled: true,
    category: 'statistic',
  },
  {
    id: 'active',
    name: 'Active Pipeline',
    description: 'Applications currently in interview stages',
    icon: <ClockCircleOutlined />,
    defaultEnabled: true,
    category: 'statistic',
  },
  {
    id: 'outcomes',
    name: 'Outcomes Summary',
    description: 'Breakdown of application outcomes',
    icon: <TrophyOutlined />,
    defaultEnabled: true,
    category: 'statistic',
  },
  {
    id: 'ghosted',
    name: 'No Response',
    description: 'Applications that were ghosted or never responded to',
    icon: <QuestionCircleOutlined />,
    defaultEnabled: true,
    category: 'statistic',
  },
  {
    id: 'locations',
    name: 'Top Locations',
    description: 'Most common office locations',
    icon: <EnvironmentOutlined />,
    defaultEnabled: true,
    category: 'chart',
  },
  {
    id: 'rounds',
    name: 'Interview Rounds',
    description: 'Distribution of interview rounds',
    icon: <AimOutlined />,
    defaultEnabled: true,
    category: 'chart',
  },
  {
    id: 'funnel',
    name: 'Application Funnel',
    description: 'Pipeline visualization',
    icon: <BarChartOutlined />,
    defaultEnabled: true,
    category: 'chart',
  },
  {
    id: 'avg_days_to_offer',
    name: 'Avg Days to Offer',
    description: 'Average time to land an offer',
    icon: <CalendarOutlined />,
    defaultEnabled: true,
    category: 'statistic',
  },
  {
    id: 'response_rate',
    name: 'Response Rate',
    description: 'Share of applications that received any response',
    icon: <LineChartOutlined />,
    defaultEnabled: false,
    category: 'statistic',
  },
  {
    id: 'offer_rate',
    name: 'Offer Rate',
    description: 'Offers as a percentage of total applications',
    icon: <ThunderboltOutlined />,
    defaultEnabled: false,
    category: 'statistic',
  },
  {
    id: 'recent_applications',
    name: 'Last 30 Days',
    description: 'Recent application volume over the last 30 days',
    icon: <ClockCircleOutlined />,
    defaultEnabled: false,
    category: 'statistic',
  },
  {
    id: 'top_companies',
    name: 'Top Companies',
    description: 'Companies you have applied to most often',
    icon: <BankOutlined />,
    defaultEnabled: false,
    category: 'chart',
  },
  {
    id: 'work_modes',
    name: 'Work Modes',
    description: 'Remote, hybrid, onsite, and unknown mix',
    icon: <ApartmentOutlined />,
    defaultEnabled: false,
    category: 'chart',
  },
];
