import type { MaritalStatusOption } from './offerTypes';
export const DEFAULT_MARITAL_STATUS_OPTIONS: MaritalStatusOption[] = [
  { code: 'SINGLE', label: 'Single' },
  { code: 'MARRIED_FILING_JOINTLY', label: 'Married Filing Jointly' },
  { code: 'MARRIED_FILING_SEPARATELY', label: 'Married Filing Separately' },
  { code: 'HEAD_OF_HOUSEHOLD', label: 'Head of Household' },
];

export const DEFAULT_CITY_COST_OF_LIVING: Record<string, number> = {
  'San Francisco, CA': 168,
  'San Jose, CA': 156,
  'Seattle, WA': 132,
  'New York, NY': 154,
  'Austin, TX': 111,
  'Chicago, IL': 117,
  'Boston, MA': 148,
  'Los Angeles, CA': 149,
  'Atlanta, GA': 104,
  'Denver, CO': 121,
  'Remote / National Average': 100,
};

export const DEFAULT_STATE_COL_BASE: Record<string, number> = {
  AL: 89,
  AK: 128,
  AZ: 104,
  AR: 88,
  CA: 134,
  CO: 112,
  CT: 115,
  DE: 103,
  FL: 102,
  GA: 97,
  HI: 186,
  ID: 101,
  IL: 101,
  IN: 90,
  IA: 89,
  KS: 90,
  KY: 91,
  LA: 92,
  ME: 108,
  MD: 112,
  MA: 123,
  MI: 92,
  MN: 98,
  MS: 86,
  MO: 90,
  MT: 101,
  NE: 92,
  NV: 105,
  NH: 111,
  NJ: 118,
  NM: 94,
  NY: 123,
  NC: 95,
  ND: 95,
  OH: 91,
  OK: 89,
  OR: 113,
  PA: 99,
  RI: 109,
  SC: 94,
  SD: 94,
  TN: 91,
  TX: 97,
  UT: 104,
  VT: 110,
  VA: 105,
  WA: 114,
  WV: 89,
  WI: 95,
  WY: 97,
  DC: 152,
};

export const DEFAULT_STATE_TAX_RATE: Record<string, number> = {
  AK: 0,
  FL: 0,
  NV: 0,
  SD: 0,
  TN: 0,
  TX: 0,
  WA: 0,
  WY: 0,
  NH: 0,
  AL: 4.5,
  AZ: 2.5,
  AR: 4.4,
  CA: 8.5,
  CO: 4.4,
  CT: 5.0,
  DE: 5.0,
  GA: 5.2,
  HI: 7.0,
  ID: 5.8,
  IL: 4.95,
  IN: 3.15,
  IA: 4.5,
  KS: 5.2,
  KY: 4.0,
  LA: 3.5,
  ME: 6.0,
  MD: 5.0,
  MA: 5.0,
  MI: 4.25,
  MN: 6.2,
  MS: 4.7,
  MO: 4.9,
  MT: 5.5,
  NE: 5.8,
  NJ: 6.0,
  NM: 4.7,
  NY: 6.8,
  NC: 4.5,
  ND: 2.5,
  OH: 3.5,
  OK: 4.8,
  OR: 7.8,
  PA: 3.07,
  RI: 5.0,
  SC: 5.4,
  UT: 4.85,
  VT: 6.0,
  VA: 4.8,
  WV: 4.5,
  WI: 5.1,
  DC: 7.0,
};

export const DEFAULT_STATE_NAME_TO_ABBR: Record<string, string> = {
  Alabama: 'AL',
  Alaska: 'AK',
  Arizona: 'AZ',
  Arkansas: 'AR',
  California: 'CA',
  Colorado: 'CO',
  Connecticut: 'CT',
  Delaware: 'DE',
  Florida: 'FL',
  Georgia: 'GA',
  Hawaii: 'HI',
  Idaho: 'ID',
  Illinois: 'IL',
  Indiana: 'IN',
  Iowa: 'IA',
  Kansas: 'KS',
  Kentucky: 'KY',
  Louisiana: 'LA',
  Maine: 'ME',
  Maryland: 'MD',
  Massachusetts: 'MA',
  Michigan: 'MI',
  Minnesota: 'MN',
  Mississippi: 'MS',
  Missouri: 'MO',
  Montana: 'MT',
  Nebraska: 'NE',
  Nevada: 'NV',
  'New Hampshire': 'NH',
  'New Jersey': 'NJ',
  'New Mexico': 'NM',
  'New York': 'NY',
  'North Carolina': 'NC',
  'North Dakota': 'ND',
  Ohio: 'OH',
  Oklahoma: 'OK',
  Oregon: 'OR',
  Pennsylvania: 'PA',
  'Rhode Island': 'RI',
  'South Carolina': 'SC',
  'South Dakota': 'SD',
  Tennessee: 'TN',
  Texas: 'TX',
  Utah: 'UT',
  Vermont: 'VT',
  Virginia: 'VA',
  Washington: 'WA',
  'West Virginia': 'WV',
  Wisconsin: 'WI',
  Wyoming: 'WY',
  'District of Columbia': 'DC',
};
